version: '2.1'

services:
  testssl: &defaults
    image: quay.io/jumanjiman/testssl:latest
    command: "--help"
    stdin_open: true
    tty: true
    read_only: true
    mem_limit: 100M
    pids_limit: 100
    cpu_shares: 512
    cap_drop:
      - all
